services:
  ollama:
    image: ollama/ollama
    #build: .
    container_name: ollama
    volumes:
      - ../backend/backup:/root/.ollama
    ports:
      - 11434:11434
    #deploy:
      #resources:
        #reservations:
          #devices:
            #- driver: nvidia
              #count: all
              #capabilities: [gpu]